require(microbenchmark)
require(jsonlite)
require(rjson)
### packages below are not good in performance
# require(RJSONIO)

#######################################################
#                                                     #
#             import data to R                        #
# e.g. data.bike <- readRDS("path of bike data")      #
#                                                     #      
#######################################################

### compare performance jsonlite vs. rjson
microbenchmark(
  jsonlite::toJSON(data.bike, pretty = TRUE),
  rjson::toJSON(as.list(data.bike)),
  times = 5  # run 5 times for each function
)

### generate json format data
system.time(
  jsonBike.jsonlite <- jsonlite::toJSON(data.bike, pretty = TRUE)
)
### foramt generated by function below is not preferrable 
# jsonBike.jsonlite.ser <- serializeJSON(data.bike, pretty = TRUE)


### foramt generated by function below is not preferrable
# system.time(
#   jsonBike.rjson <- rjson::toJSON(as.list(data.bike))
# )

### for comparison only, not for use cuz too bad in performance
# system.time(
#   jsonBike.RJSONIO <- RJSONIO::toJSON(data.bike, byrow = TRUE)
# )

### choose one of both ways below
write(jsonBike.jsonlite, file = "jsonlite.JSON")
write(jsonBike.jsonlite, file = "jsonlite.txt")
### serialized json format is not acceptable, so give it up
# write(jsonBike.jsonlite.ser, file = "jsonliteSer.JSON")

### rjson functions lose in competition, so give it up as well
# write(jsonBike.rjson, file = "rjson.JSON")
# write(jsonBike.rjson, file = "rjson.txt")



### build an another data.table but with rownames
data.bikeWithRowName <- data.bike
row.names(data.bikeWithRowName) <- paste(data.bikeWithRowName$dateTime, 
                                         data.bikeWithRowName$stopName, 
                                         sep = " ")

### generate json format data
system.time(
  jsonBikeWithRowName.jsonlite <- jsonlite::toJSON(data.bikeWithRowName, pretty = TRUE)
)

### export
write(jsonBikeWithRowName.jsonlite, file = "jsonliteWithRowName.txt")

